In [1]:
from fno import Net2d
import torch
import torch.nn as nn

In [10]:
b = a.flatten(start_dim=0, end_dim=1)
b = b.unsqueeze(1)
b = b.reshape(10, 5, 1, 3, 3)
print(b.shape)
print(b[0, 0, :, :])
print(b[-1, -1, :, :])
b = b.flatten(start_dim=1, end_dim=2)
print(b.shape)
print(b[0, 0, :, :])
print(b[-1, -1, :, :])


torch.Size([10, 5, 1, 3, 3])
tensor([[[-0.5771, -1.2310, -0.8760],
         [-1.6162, -2.5681,  0.1564],
         [ 0.9137,  0.8912, -1.5376]]])
tensor([[[ 0.8716, -1.4187, -0.7957],
         [-0.1223,  0.6164, -0.6945],
         [ 1.3738, -0.3663,  1.4960]]])
torch.Size([10, 5, 3, 3])
tensor([[-0.5771, -1.2310, -0.8760],
        [-1.6162, -2.5681,  0.1564],
        [ 0.9137,  0.8912, -1.5376]])
tensor([[ 0.8716, -1.4187, -0.7957],
        [-0.1223,  0.6164, -0.6945],
        [ 1.3738, -0.3663,  1.4960]])


In [4]:
a = torch.randn(10, 5, 3, 3)
print(a[0,0,:,:])
print(a[-1,-1,:,:])

tensor([[-0.5771, -1.2310, -0.8760],
        [-1.6162, -2.5681,  0.1564],
        [ 0.9137,  0.8912, -1.5376]])
tensor([[ 0.8716, -1.4187, -0.7957],
        [-0.1223,  0.6164, -0.6945],
        [ 1.3738, -0.3663,  1.4960]])


In [25]:
c = torch.tensor([1.0, 2.0, 3.0]).reshape(3, 1)
c = c.unsqueeze(-1)
c = c.unsqueeze(-1)
c = c.unsqueeze(0)
print(c.shape)
c = c.repeat(10, 1, 1, 4, 4)
print(c.shape)
print(c[:, 1])

torch.Size([1, 3, 1, 1, 1])
torch.Size([10, 3, 1, 4, 4])
tensor([[[[2., 2., 2., 2.],
          [2., 2., 2., 2.],
          [2., 2., 2., 2.],
          [2., 2., 2., 2.]]],


        [[[2., 2., 2., 2.],
          [2., 2., 2., 2.],
          [2., 2., 2., 2.],
          [2., 2., 2., 2.]]],


        [[[2., 2., 2., 2.],
          [2., 2., 2., 2.],
          [2., 2., 2., 2.],
          [2., 2., 2., 2.]]],


        [[[2., 2., 2., 2.],
          [2., 2., 2., 2.],
          [2., 2., 2., 2.],
          [2., 2., 2., 2.]]],


        [[[2., 2., 2., 2.],
          [2., 2., 2., 2.],
          [2., 2., 2., 2.],
          [2., 2., 2., 2.]]],


        [[[2., 2., 2., 2.],
          [2., 2., 2., 2.],
          [2., 2., 2., 2.],
          [2., 2., 2., 2.]]],


        [[[2., 2., 2., 2.],
          [2., 2., 2., 2.],
          [2., 2., 2., 2.],
          [2., 2., 2., 2.]]],


        [[[2., 2., 2., 2.],
          [2., 2., 2., 2.],
          [2., 2., 2., 2.],
          [2., 2., 2., 2.]]],


        [[[2., 

In [3]:
import torch

In [5]:
wavelen = [0.443, 0.490, 0.560, 0.665, 0.705, 0.740, 0.783, 0.842, 0.865, 0.945, 1.610, 2.190]
wavelen = torch.tensor(wavelen).reshape(12, 1).unsqueeze(-1).unsqueeze(-1).unsqueeze(0)
print(wavelen.shape)
wave = wavelen.repeat(32, 1, 1, 120, 120)

torch.Size([1, 12, 1, 1, 1])


In [13]:
print(wave.shape)
print(wave[2, 3, :, :, :])

torch.Size([32, 12, 1, 120, 120])
tensor([[[0.6650, 0.6650, 0.6650,  ..., 0.6650, 0.6650, 0.6650],
         [0.6650, 0.6650, 0.6650,  ..., 0.6650, 0.6650, 0.6650],
         [0.6650, 0.6650, 0.6650,  ..., 0.6650, 0.6650, 0.6650],
         ...,
         [0.6650, 0.6650, 0.6650,  ..., 0.6650, 0.6650, 0.6650],
         [0.6650, 0.6650, 0.6650,  ..., 0.6650, 0.6650, 0.6650],
         [0.6650, 0.6650, 0.6650,  ..., 0.6650, 0.6650, 0.6650]]])


In [20]:
x_all = torch.ones(32, 1, 120, 120)
for i in range(11):
    x = torch.ones(32, 1, 120, 120) * (i+2)
    x_all = torch.cat((x_all, x), dim=1)


In [21]:
x_all = x_all.unsqueeze(2)
print(x_all.shape)
newx = torch.cat((x_all, wave), dim=2)

torch.Size([32, 12, 1, 120, 120])


In [24]:
print(newx.shape)
print(newx[1, :, :, 2, 3])

torch.Size([32, 12, 2, 120, 120])
tensor([[ 1.0000,  0.4430],
        [ 2.0000,  0.4900],
        [ 3.0000,  0.5600],
        [ 4.0000,  0.6650],
        [ 5.0000,  0.7050],
        [ 6.0000,  0.7400],
        [ 7.0000,  0.7830],
        [ 8.0000,  0.8420],
        [ 9.0000,  0.8650],
        [10.0000,  0.9450],
        [11.0000,  1.6100],
        [12.0000,  2.1900]])


In [ ]:
from fno import Net2d
from resnet import resnet20
class ConvWeightGen(nn.Module):
    def __init__(self, in_channels, out_channels, kernel_size, in_dim, hidden_dim):
        # input: condition used to generate the weights (shape: indim)
        # output: weights for convolutional layer (shape: out_channels, in_channels, kernel_size, kernel_size)
        super(ConvWeightGen, self).__init__()
        self.in_channels = in_channels
        self.out_channels = out_channels
        self.kernel_size = kernel_size
        self.indim = in_dim
        self.layers = []
        for i in range(in_channels):
            self.layer.append(nn.Linear(in_dim, hidden_dim))
        self.linear = nn.Linear(hidden_dim, out_channels * kernel_size * kernel_size)
    def forward(self, x):
        # x: condition used to generate the weights (shape: indim)
        # return: weights for convolutional layer (shape: out_channels, in_channels, kernel_size, kernel_size)
        xlist = []
        x_copy = x.copy()
        for i in range(self.in_channels):
            intermd = self.layers[i](x_copy)
            intermd = self.linear(intermd) # shape: out_channels * kernel_size * kernel_size
            intermd = intermd.reshape(self.out_channels, self.kernel_size, self.kernel_size)
            xlist.append(intermd)
        return torch.stack(xlist, dim=1)
    
class WaveModule(nn.Module):
    def __init__(self, in_channels, out_channels, kernel_size, stride, padding, in_dim, hidden_dim, batch_size, num_band):
        super(WaveModule, self).__init__()
        # in_channels = 1
        # out_channels = 16
        self.in_channels = in_channels
        self.out_channels = out_channels
        self.conv_weight_gen = ConvWeightGen(in_channels, out_channels, kernel_size, in_dim, hidden_dim)
        self.conv_static = nn.Conv2d(in_channels, out_channels, kernel_size, stride, padding)
        self.conv_dynamic = nn.Conv2d(in_channels*batch_size*num_band, out_channels*batch_size*num_band, kernel_size, stride, padding, groups=batch_size*num_band)

    def forward(self, x, wave):
        # x: (batch_size, num_band*in_channel, h, w)
        # wave: (num_band, 1)
        b, _, h, w = x.shape
        c = wave.shape[0]
        wave = wave.repeat(b, 1) # shape: batch_size*num_band, 1
        x = x.reshape(b, c, self.in_channels, h, w) # shape: batch_size, num_band, in_channels, h, w
        x = x.flatten(start_dim=0, end_dim=1) # shape: batch_size*num_band, in_channels, h, w
        gen_weight = self.conv_weight_gen(wave) # shape: batch_size*num_band, out_channels, in_channels, kernel_size, kernel_size
        self.conv_dynamic.weight = gen_weight.flatten(start_dim=0, end_dim=1) # shape: batch_size*num_band*out_channels, in_channels, kernel_size, kernel_size
        static_output = self.conv_static(x).reshape(b, c, self.out_channels, h, w).flatten(start_dim=1, end_dim=2) # shape: batch_size, num_band*out_channels, h, w
        dynamic_output = self.conv_dynamic(x.flatten(start_dim=0, end_dim=1).unsqueeze(0)).squeeze(0).reshape(b, c*self.out_channels, h, w)
        return static_output + dynamic_output
    
class DynEmbedder(nn.Module):
    def __init__(self, mid_channels, out_channels, kernel_size, stride, padding, in_dim, hidden_dim, batch_size, num_band):
        super(DynEmbedder, self).__init__()
        self.wave_module1 = WaveModule(1, mid_channels, kernel_size, stride, padding, in_dim, hidden_dim, batch_size, num_band)
        self.wave_module2 = WaveModule(mid_channels, out_channels, kernel_size, stride, padding, in_dim, hidden_dim, batch_size, num_band)
        self.embedder = resnet20(in_channel = num_band*mid_channels, num_classes = num_band*mid_channels, remain_shape = True)
    def forward(self, x, wave):
        # x: (batch_size, num_band*in_channel, h, w)
        # wave: (num_band, 1)
        x = self.wave_module1(x, wave)
        x = self.embedder(x)
        x = self.wave_module2(x, wave)
        return x
        

In [3]:
import torch
import torch.nn as nn

In [11]:
conv = nn.Conv2d(2, 4, 3, 1, 1, groups=2)
print(conv.weight.shape)
conv.weight = nn.Parameter(torch.cat((torch.zeros(2, 1, 3, 3), torch.ones(2, 1, 3, 3)), dim=0))
conv.bias = nn.Parameter(torch.zeros(4))
x = torch.ones(1, 2, 5, 5)
y = conv(x)
print(y.shape)
print(y[0,:,1,1])


torch.Size([4, 1, 3, 3])
torch.Size([1, 4, 5, 5])
tensor([0., 0., 9., 9.], grad_fn=<SelectBackward0>)


In [18]:
x = torch.cat((torch.ones(1,3,3), torch.ones(1,3,3)*2, torch.ones(1,3,3)*3), dim=0)
x = x.flatten(start_dim=0, end_dim=1)
x = x.reshape(3,3,3)
print(x[:3,0,0])


tensor([1., 2., 3.])
